# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dock.ui'
#
# Created: Tue Nov 25 14:45:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_pyivmm(object):
    def setupUi(self, pyivmm):
        pyivmm.setObjectName(_fromUtf8("pyivmm"))
        pyivmm.resize(356, 222)
        pyivmm.setFloating(False)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.mapLoadTab = QtGui.QWidget()
        self.mapLoadTab.setObjectName(_fromUtf8("mapLoadTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.mapLoadTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.mapLoadTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.roadLineEdit = QtGui.QLineEdit(self.mapLoadTab)
        self.roadLineEdit.setReadOnly(True)
        self.roadLineEdit.setObjectName(_fromUtf8("roadLineEdit"))
        self.horizontalLayout_2.addWidget(self.roadLineEdit)
        self.roadLoadButton = QtGui.QPushButton(self.mapLoadTab)
        self.roadLoadButton.setObjectName(_fromUtf8("roadLoadButton"))
        self.horizontalLayout_2.addWidget(self.roadLoadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.mapLoadTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.centerLineEdit = QtGui.QLineEdit(self.mapLoadTab)
        self.centerLineEdit.setReadOnly(False)
        self.centerLineEdit.setObjectName(_fromUtf8("centerLineEdit"))
        self.horizontalLayout_3.addWidget(self.centerLineEdit)
        self.gotoButton = QtGui.QPushButton(self.mapLoadTab)
        self.gotoButton.setObjectName(_fromUtf8("gotoButton"))
        self.horizontalLayout_3.addWidget(self.gotoButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_7 = QtGui.QLabel(self.mapLoadTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        self.crossLineEdit = QtGui.QLineEdit(self.mapLoadTab)
        self.crossLineEdit.setObjectName(_fromUtf8("crossLineEdit"))
        self.horizontalLayout.addWidget(self.crossLineEdit)
        self.goToCrossButton = QtGui.QPushButton(self.mapLoadTab)
        self.goToCrossButton.setObjectName(_fromUtf8("goToCrossButton"))
        self.horizontalLayout.addWidget(self.goToCrossButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 127, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.tabWidget.addTab(self.mapLoadTab, _fromUtf8(""))
        self.shortestPathTab = QtGui.QWidget()
        self.shortestPathTab.setEnabled(False)
        self.shortestPathTab.setObjectName(_fromUtf8("shortestPathTab"))
        self.gridLayout = QtGui.QGridLayout(self.shortestPathTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.shortestPathTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.beginPointLineEdit = QtGui.QLineEdit(self.shortestPathTab)
        self.beginPointLineEdit.setReadOnly(True)
        self.beginPointLineEdit.setObjectName(_fromUtf8("beginPointLineEdit"))
        self.gridLayout.addWidget(self.beginPointLineEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.shortestPathTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.endPointLineEdit = QtGui.QLineEdit(self.shortestPathTab)
        self.endPointLineEdit.setReadOnly(True)
        self.endPointLineEdit.setObjectName(_fromUtf8("endPointLineEdit"))
        self.gridLayout.addWidget(self.endPointLineEdit, 0, 3, 1, 1)
        self.pickPointButton = QtGui.QPushButton(self.shortestPathTab)
        self.pickPointButton.setObjectName(_fromUtf8("pickPointButton"))
        self.gridLayout.addWidget(self.pickPointButton, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.shortestPathTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.shortestLengthLabel = QtGui.QLabel(self.shortestPathTab)
        self.shortestLengthLabel.setText(_fromUtf8(""))
        self.shortestLengthLabel.setObjectName(_fromUtf8("shortestLengthLabel"))
        self.gridLayout.addWidget(self.shortestLengthLabel, 1, 1, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(20, 139, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 2, 1, 1)
        self.tabWidget.addTab(self.shortestPathTab, _fromUtf8(""))
        self.gpsTab = QtGui.QWidget()
        self.gpsTab.setEnabled(False)
        self.gpsTab.setObjectName(_fromUtf8("gpsTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gpsTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(20, 163, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 2, 1, 1)
        self.gpsLoadButton = QtGui.QPushButton(self.gpsTab)
        self.gpsLoadButton.setObjectName(_fromUtf8("gpsLoadButton"))
        self.gridLayout_2.addWidget(self.gpsLoadButton, 0, 4, 1, 1)
        self.candidateCreateButton = QtGui.QPushButton(self.gpsTab)
        self.candidateCreateButton.setObjectName(_fromUtf8("candidateCreateButton"))
        self.gridLayout_2.addWidget(self.candidateCreateButton, 2, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.gpsTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.radiousSpine = QtGui.QDoubleSpinBox(self.gpsTab)
        self.radiousSpine.setMaximum(500.0)
        self.radiousSpine.setObjectName(_fromUtf8("radiousSpine"))
        self.gridLayout_2.addWidget(self.radiousSpine, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.gpsTab)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 2, 2, 1, 1)
        self.limitSpine = QtGui.QSpinBox(self.gpsTab)
        self.limitSpine.setMinimum(1)
        self.limitSpine.setObjectName(_fromUtf8("limitSpine"))
        self.gridLayout_2.addWidget(self.limitSpine, 2, 3, 1, 1)
        self.trajLoadButton = QtGui.QPushButton(self.gpsTab)
        self.trajLoadButton.setObjectName(_fromUtf8("trajLoadButton"))
        self.gridLayout_2.addWidget(self.trajLoadButton, 3, 4, 1, 1)
        self.trajText = QtGui.QLineEdit(self.gpsTab)
        self.trajText.setObjectName(_fromUtf8("trajText"))
        self.gridLayout_2.addWidget(self.trajText, 3, 0, 1, 4)
        self.gpsFileLineEdit = QtGui.QLineEdit(self.gpsTab)
        self.gpsFileLineEdit.setReadOnly(True)
        self.gpsFileLineEdit.setObjectName(_fromUtf8("gpsFileLineEdit"))
        self.gridLayout_2.addWidget(self.gpsFileLineEdit, 0, 0, 1, 4)
        self.rawTrajButton = QtGui.QPushButton(self.gpsTab)
        self.rawTrajButton.setObjectName(_fromUtf8("rawTrajButton"))
        self.gridLayout_2.addWidget(self.rawTrajButton, 1, 4, 1, 1)
        self.tabWidget.addTab(self.gpsTab, _fromUtf8(""))
        self.ivmmTab = QtGui.QWidget()
        self.ivmmTab.setEnabled(False)
        self.ivmmTab.setObjectName(_fromUtf8("ivmmTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.ivmmTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_11 = QtGui.QLabel(self.ivmmTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.projectDistMuLineEdit = QtGui.QLineEdit(self.ivmmTab)
        self.projectDistMuLineEdit.setObjectName(_fromUtf8("projectDistMuLineEdit"))
        self.gridLayout_3.addWidget(self.projectDistMuLineEdit, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.ivmmTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 2, 1, 1)
        self.projectDistStddevLineEdit = QtGui.QLineEdit(self.ivmmTab)
        self.projectDistStddevLineEdit.setObjectName(_fromUtf8("projectDistStddevLineEdit"))
        self.gridLayout_3.addWidget(self.projectDistStddevLineEdit, 0, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.ivmmTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.betaLineEdit = QtGui.QLineEdit(self.ivmmTab)
        self.betaLineEdit.setObjectName(_fromUtf8("betaLineEdit"))
        self.gridLayout_3.addWidget(self.betaLineEdit, 1, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.ivmmTab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.queryRadiousLineEdit = QtGui.QLineEdit(self.ivmmTab)
        self.queryRadiousLineEdit.setObjectName(_fromUtf8("queryRadiousLineEdit"))
        self.gridLayout_3.addWidget(self.queryRadiousLineEdit, 1, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.ivmmTab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.candidateLimitSpine = QtGui.QSpinBox(self.ivmmTab)
        self.candidateLimitSpine.setMinimum(1)
        self.candidateLimitSpine.setObjectName(_fromUtf8("candidateLimitSpine"))
        self.gridLayout_3.addWidget(self.candidateLimitSpine, 2, 1, 1, 1)
        self.ivmmComputeButton = QtGui.QPushButton(self.ivmmTab)
        self.ivmmComputeButton.setObjectName(_fromUtf8("ivmmComputeButton"))
        self.gridLayout_3.addWidget(self.ivmmComputeButton, 2, 3, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 108, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 3, 0, 1, 4)
        self.tabWidget.addTab(self.ivmmTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        pyivmm.setWidget(self.dockWidgetContents)

        self.retranslateUi(pyivmm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pyivmm)
        pyivmm.setTabOrder(self.roadLineEdit, self.beginPointLineEdit)
        pyivmm.setTabOrder(self.beginPointLineEdit, self.endPointLineEdit)
        pyivmm.setTabOrder(self.endPointLineEdit, self.pickPointButton)
        pyivmm.setTabOrder(self.pickPointButton, self.gpsFileLineEdit)
        pyivmm.setTabOrder(self.gpsFileLineEdit, self.gpsLoadButton)
        pyivmm.setTabOrder(self.gpsLoadButton, self.candidateCreateButton)
        pyivmm.setTabOrder(self.candidateCreateButton, self.projectDistMuLineEdit)
        pyivmm.setTabOrder(self.projectDistMuLineEdit, self.betaLineEdit)

    def retranslateUi(self, pyivmm):
        pyivmm.setWindowTitle(_translate("pyivmm", "pyivmm", None))
        self.label_4.setText(_translate("pyivmm", "道路", None))
        self.roadLoadButton.setText(_translate("pyivmm", "载入道路", None))
        self.label_5.setText(_translate("pyivmm", "视角", None))
        self.gotoButton.setText(_translate("pyivmm", "前往", None))
        self.label_7.setText(_translate("pyivmm", "路口", None))
        self.goToCrossButton.setText(_translate("pyivmm", "前往", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mapLoadTab), _translate("pyivmm", "载入地图", None))
        self.label.setText(_translate("pyivmm", "起点", None))
        self.label_2.setText(_translate("pyivmm", "终点", None))
        self.pickPointButton.setText(_translate("pyivmm", "拾取", None))
        self.label_3.setText(_translate("pyivmm", "路径长度", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shortestPathTab), _translate("pyivmm", "最短路径", None))
        self.gpsLoadButton.setText(_translate("pyivmm", "加载GPS数据", None))
        self.candidateCreateButton.setText(_translate("pyivmm", "生成候选点", None))
        self.label_6.setText(_translate("pyivmm", "半径", None))
        self.label_17.setText(_translate("pyivmm", "限制", None))
        self.trajLoadButton.setText(_translate("pyivmm", "轨迹加载", None))
        self.rawTrajButton.setText(_translate("pyivmm", "原始轨迹", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gpsTab), _translate("pyivmm", "GPS加载", None))
        self.label_11.setText(_translate("pyivmm", "偏差距离均值", None))
        self.label_12.setText(_translate("pyivmm", "偏差标准差", None))
        self.label_13.setText(_translate("pyivmm", "距离加权参数", None))
        self.label_14.setText(_translate("pyivmm", "候选半径", None))
        self.label_16.setText(_translate("pyivmm", "候选点数量限制", None))
        self.ivmmComputeButton.setText(_translate("pyivmm", "生成", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ivmmTab), _translate("pyivmm", "IVMM", None))

